// Generated by CoffeeScript 1.8.0
(function() {
  var ctx, data, myNewChart, myPieChart, options;

  $(function() {
    return $('#accordion').accordion({
      collapsable: true
    });
  });
}).call(this);
